### ISSUE TITLE
Suppose one is a lisp newbie... (like me)

### ISSUE THREAD

**Issue by ryanizer** [terminal625/sucle#2]
What CL implementation are you using?

Improved config and build instructions wouldn't hurt.

**Comment by terminal625** [comment]
Hi ryanizer! 
This is developed and used mainly with [SBCL](http://www.sbcl.org/). 
[Here are the installation directions](https://github.com/terminal625/sucle/blob/master/INSTALL.md)
If something is unclear or confusing or does not work please let me know

**Comment by ryanizer** [comment]
Awesome, will check it out!
Thanks
