### ISSUE TITLE
apt-get install libglfw3-dev

### ISSUE THREAD

**Issue by shirok** [terminal625/sucle#4]
Hi!  Just a nitpick, but on Ubuntu 16.04, I needed `apt-get install libglfw3-dev` (instead of `libglfw3` as described in current INSTALL.md) to compile.

**Comment by terminal625** [comment]
Well, thanks for the nitpick! There's no way I would have found that.
[commit](https://github.com/terminal625/sucle/commit/b472188baed16f2f6e02d1c64c6a4871ad520170)
